Repository MicroClub-USTHB/Hacktoberfest-2k19, pull requests merged in 2019-10, with the labels that each got.

#28 fixed typos in readme.md
  README.md
  README_FRENCH.md
Labels: Hacktoberfest, enhancement

#29 adds profiles/shellc0d3.md and myOctocat/shellc0d3_Billie_octocat.png
  myOctocat/shellc0d3_Billie_octocat.png
  profiles/shellc0d3.md
Labels: Hacktoberfest, good first issue

#30 Added a profile page and Updated the cipher in the ransomware
  Projects/C/Crypto_ransomware/ListesChaines.h
  Projects/C/Crypto_ransomware/main.c
  profiles/MOULOUDI_Mohamed_Lyes.md
Labels: Hacktoberfest, enhancement, good first issue

#36 (Hacktoberfest) Updating profiles and myOctocat folders
  myOctocat/cr105ph1nx_Violent_bunny_octocat.png
  profiles/cr105ph1nx.md
Labels: Hacktoberfest, good first issue

#37 Add profile
  myOctocat/Ofest.png
  profiles/x1nn1e.md
Labels: Hacktoberfest, good first issue :beginner:

#42 JavaScript d3.js project 2
  Js_d3_Statestics-2/Js_d3_Statestics-2.html
  Js_d3_Statestics-2/ReadMe.md
  Js_d3_Statestics-2/d3.v3.js
  Projects/JavaScript/Js_d3_Statestics-1/ReadMe.md
  Projects/JavaScript/Js_d3_Statestics-1/UTSHB-dep-hierarchy.html
  Projects/JavaScript/Js_d3_Statestics-1/d3.v4.min.js
  Projects/JavaScript/Js_d3_Statestics-2/Js_d3_Statestics-2.html
  Projects/JavaScript/Js_d3_Statestics-2/ReadMe.md
  Projects/JavaScript/Js_d3_Statestics-2/d3.v3.js
  myOctocat/ML-octocat.png
  profiles/Amel Profil.md
Labels: Hacktoberfest, good first issue :beginner:

#46 Add MIT license #44
  LICENSE
Labels: Hacktoberfest, good first issue :beginner:

#50 Updated Project's README file
  Projects/ProjectsContributionRules.md
Labels: Hacktoberfest, documentation :page_with_curl:, enhancement, good first issue :beginner:

#52 Added translation to Brazilian portuguese
  translations/README_FRENCH.md
  translations/README_pt_br.md
Labels: Hacktoberfest, documentation :page_with_curl:, enhancement, good first issue :beginner:

#61 Create oussamah
  profiles/oussamah
Labels: Hacktoberfest, good first issue :beginner:

#62 a mini JavaScript game
  Projects/JavaScript/MiniGameJS/board.jpg
  Projects/JavaScript/MiniGameJS/code.js
  Projects/JavaScript/MiniGameJS/index.html
Labels: Hacktoberfest, good first issue :beginner:

#77 Creation of Adel_Abderrahmane_BELHIMER.md
  myOctocat/AdelAbderrahmae_BELHIMER_Designer!.png
  profiles/Adel_Abderrahmane_BELHIMER
Labels: Hacktoberfest, good first issue :beginner:

#83 CSS
  docs/index.html
  docs/style.css
  docs/style2.css
Labels: Hacktoberfest, enhancement

#69 Change readme file name, so github can show it
  Projects/JavaScript/README.md
Labels: Hacktoberfest, good first issue :beginner:

#70 add links to README translations
  README.md
  translations/README_FRENCH.md
  translations/README_pt_br.md
Labels: Hacktoberfest, documentation :page_with_curl:, good first issue :beginner:

#68 Correct html-css markdown
  Projects/HTML-CSS/HTML-CSS.md
Labels: Hacktoberfest, documentation :page_with_curl:, good first issue :beginner:

#65 Create lava.md
  profiles/lava.md
Labels: Hacktoberfest, documentation :page_with_curl:, good first issue :beginner:

#48 add readme.md translation INDONESIA
  translations/README_INDONESIA.md
Labels: Hacktoberfest, documentation :page_with_curl:, good first issue :beginner:

#91 Create REBEI Yassine Raouf.md
  myOctocat/REBEI Yassine Raouf.png
  profiles/REBEI Yassine Raouf.md
Labels: Hacktoberfest, good first issue :beginner:

#93 Web project
  Projects/Web/Feedback/README.md
  Projects/Web/Feedback/css/main.css
  Projects/Web/Feedback/css/util.css
  Projects/Web/Feedback/images/icons/favicon.ico
  Projects/Web/Feedback/images/icons/map-marker.png
  Projects/Web/Feedback/include/config.php
  Projects/Web/Feedback/index.php
  Projects/Web/Feedback/js/main.js
  Projects/Web/Feedback/messages.sql
  Projects/Web/Feedback/vendor/animate/animate.css
  Projects/Web/Feedback/vendor/animsition/css/animsition.css
  Projects/Web/Feedback/vendor/animsition/css/animsition.min.css
  Projects/Web/Feedback/vendor/animsition/js/animsition.js
  Projects/Web/Feedback/vendor/animsition/js/animsition.min.js
  Projects/Web/Feedback/vendor/bootstrap/css/bootstrap-grid.css
  Projects/Web/Feedback/vendor/bootstrap/css/bootstrap-grid.css.map
  Projects/Web/Feedback/vendor/bootstrap/css/bootstrap-grid.min.css
  Projects/Web/Feedback/vendor/bootstrap/css/bootstrap-grid.min.css.map
  Projects/Web/Feedback/vendor/bootstrap/css/bootstrap-reboot.css
  Projects/Web/Feedback/vendor/bootstrap/css/bootstrap-reboot.css.map
  Projects/Web/Feedback/vendor/bootstrap/css/bootstrap-reboot.min.css
  Projects/Web/Feedback/vendor/bootstrap/css/bootstrap-reboot.min.css.map
  Projects/Web/Feedback/vendor/bootstrap/css/bootstrap.css
  Projects/Web/Feedback/vendor/bootstrap/css/bootstrap.css.map
  Projects/Web/Feedback/vendor/bootstrap/css/bootstrap.min.css
  Projects/Web/Feedback/vendor/bootstrap/css/bootstrap.min.css.map
  Projects/Web/Feedback/vendor/bootstrap/js/bootstrap.js
  Projects/Web/Feedback/vendor/bootstrap/js/bootstrap.min.js
  Projects/Web/Feedback/vendor/bootstrap/js/popper.js
  Projects/Web/Feedback/vendor/bootstrap/js/popper.min.js
  Projects/Web/Feedback/vendor/bootstrap/js/tooltip.js
  Projects/Web/Feedback/vendor/countdowntime/countdowntime.js
  Projects/Web/Feedback/vendor/css-hamburgers/hamburgers.css
  Projects/Web/Feedback/vendor/css-hamburgers/hamburgers.min.css
  Projects/Web/Feedback/vendor/daterangepicker/daterangepicker.css
  Projects/Web/Feedback/vendor/daterangepicker/daterangepicker.js
  Projects/Web/Feedback/vendor/daterangepicker/moment.js
  Projects/Web/Feedback/vendor/daterangepicker/moment.min.js
  Projects/Web/Feedback/vendor/jquery/jquery-3.2.1.min.js
  Projects/Web/Feedback/vendor/perfect-scrollbar/perfect-scrollbar.css
  Projects/Web/Feedback/vendor/perfect-scrollbar/perfect-scrollbar.min.js
  Projects/Web/Feedback/vendor/select2/select2.css
  Projects/Web/Feedback/vendor/select2/select2.js
  Projects/Web/Feedback/vendor/select2/select2.min.css
  Projects/Web/Feedback/vendor/select2/select2.min.js
Labels: Hacktoberfest, good first issue :beginner:

#99 OpenGL
  Projects/C++/OpenGL-miniProject/Projet Fait Par.txt
  Projects/C++/OpenGL-miniProject/README.md
  Projects/C++/OpenGL-miniProject/SIProject.cbp
  Projects/C++/OpenGL-miniProject/SIProject.depend
  Projects/C++/OpenGL-miniProject/SIProject.layout
  Projects/C++/OpenGL-miniProject/bin/Debug/SIProject.exe
  Projects/C++/OpenGL-miniProject/main.cpp
  Projects/C++/OpenGL-miniProject/obj/Debug/main.o
Labels: Hacktoberfest

#102 Linking another student club repo/ (issue #66)
  README.md
Labels: Hacktoberfest, enhancement

#103 Update README.md
  README.md
Labels: Hacktoberfest, enhancement
